extends Resource

const MAZE_COLUMNS = 8
const MAZE_ROWS = 8
const CELL_WIDTH = 32
const CELL_HEIGHT = 32
const BOARD_COLUMNS = 21
const BOARD_ROWS = 21
const BOARD_CENTER_COLUMN = 10
const BOARD_CENTER_ROW = 10
const INVENTORY_COLUMNS = 5
const INVENTORY_ROWS = 5
const QUANTITIES_STEP_X = 4
const QUANTITIES_STEP_Y = 2
const QUANTITIES_COLUMNS = INVENTORY_COLUMNS * QUANTITIES_STEP_X
const QUANTITIES_ROWS = INVENTORY_ROWS * QUANTITIES_STEP_Y

